# Generated by Django 5.0.2 on 2024-02-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
