# Generated by Django 5.0.2 on 2024-03-02 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField(default=-1)),
                ('text', models.CharField(default='Hello User', max_length=300)),
                ('viewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField(default=-1)),
                ('text', models.CharField(default='000000', max_length=6)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='Unknown User', max_length=50)),
                ('regid', models.CharField(default='NA', max_length=15)),
                ('acayear', models.IntegerField(default=1990)),
                ('dept', models.CharField(default='select', max_length=50)),
                ('email', models.CharField(default='NA', max_length=50)),
                ('mobno', models.CharField(default='NA', max_length=10)),
                ('usertype', models.CharField(default='st', max_length=2)),
                ('verified', models.BooleanField(default=False)),
                ('verify_applied', models.BooleanField(default=False)),
                ('mentor', models.IntegerField(default=-1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
