# Generated by Django 5.0.2 on 2024-03-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashcode', models.CharField(default='0', max_length=256)),
                ('previoushash', models.CharField(default='0', max_length=256)),
                ('data', models.CharField(default='0', max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
