# Generated by Django 5.0.2 on 2024-03-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
